<?php
/**
 * Created by Kane
 * Date: 2021/5/18
 */

namespace datatom\test;


use datatom\casTools\Auth;
use datatom\casTools\CasToken;
use Exception;
use PHPUnit\Framework\TestCase;

class CasTokenTest extends TestCase {

    private $correctAuth;
    private $wrongAuth;
    private $host = "http://192.168.60.58:8000/api/";

    public function setUp(): void {
        parent::setUp(); // TODO: Change the autogenerated stub

        $key = "Ncgimi5xj7sFaX1sBLlOUfGZdNd5u4IDvDIj23I1DPg";
        $secret = "Hiw3FChphDRAr6tGXDFElcxM3j8GFnyP9fgpdjApvjI";
        $this->correctAuth = new Auth($key, $secret, $this->host);
        $this->wrongAuth = new Auth($key, "abc", $this->host);
    }

    public function testURL() {
        $token = new CasToken($this->correctAuth, "php://stdout");
        $url = $this->host .$token->getApi();
        $this->assertEquals($url, $token->getUrl());
    }

    public function testToken() {
        $token = new CasToken($this->correctAuth, "php://stdout");
//        $ret = $token->verifyToken("aff47aa0fcee40558291228ff7fd904d");
//        $this->assertArrayHasKey("account_id", $ret);

        $this->expectException(Exception::class);
        $ret = $token->verifyToken("123");
    }

    public function testAuth() {
        $token = new CasToken($this->wrongAuth, "php://stdout");
        $this->expectException(Exception::class);
        $ret = $token->verifyToken("123");
    }
}